services:
  haproxy1-ssl:
    container_name: haproxy1-ssl
    build: ./haproxy1-ssl
    volumes:
      - "./haproxy1-ssl/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "8080:443"
    depends_on:
      haproxy1-int:
        condition: service_healthy
  haproxy1-int:
    container_name: haproxy1-int
    build: ./haproxy1-int
    volumes:
      - "./haproxy1-int/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "443:80"
      - "8404:8404"
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      java1:
        condition: service_started
      java2:
        condition: service_started
  java1:
    container_name: java1
    image: nginx:latest   
  java2:
    container_name: java2
    image: nginx:latest
  redis-master:
    container_name: redis-master
    image: redis:8.2.5-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "muyfacil", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - "./redis/master/redis.conf:/etc/redis/redis.conf"
      - redis-master:/data
    command: redis-server /etc/redis/redis.conf
  redis-slave:
    container_name: redis-slave
    image: redis:8.2.5-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "muyfacil", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - "./redis/slave/redis.conf:/etc/redis/redis.conf"
      - redis-slave:/data
    command: redis-server /etc/redis/redis.conf
  redis-sentinel:
    container_name: redis-sentinel
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_SENTINEL_MASTER_NAME=mymaster
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=muyfacil
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave:
        condition: service_healthy
  solr:
    container_name: solr
    image: solr:9.10.1 
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr
  webdav:
    container_name: webdav
    build: ./webdav
    ports:
      - "8081:80"
    volumes:
      - webdav:/usr/local/apache2/htdocs/
      - webdav-up:/usr/local/apache2/uploads
      - webdav-var:/usr/local/apache2/var
  ldap:
    container_name: ldap
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ROOT=dc=empresa,dc=com
      - LDAP_ADMIN_USERNAME=admin 
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_ORGANISATION=apptest
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  
volumes:
  redis-master:
  redis-slave:
  solr:
  webdav:
  webdav-up:
  webdav-var:
  ldap_data:
  ldap_config:
